[package]
name = "set-encoding"
version = "0.1.0"
authors = ["Sergey Shandar"]
description = "Finite Set Binary Encoding"
license = "Apache-2.0"
repository = "https://github.com/rust-common/set-encoding"

[dependencies]
bitrw = "^0.8.3"
int = "^0.3.0"
tbe = "^0.3.3"
num-traits = "^0.2.6"